const path = '../assets/';

export const AppImages = {
  slider1: require(`${path}slider-1.png`),
  slider2: require(`${path}slider-2.png`),
  slider3: require(`${path}slider-3.png`),
  slider4: require(`${path}slider-4.png`),
  ProfileSlider: require(`${path}Profile1.png`),
  success: require(`${path}svg.png`),
  bb1: require(`${path}barberImage1.png`),
  mapImg: require(`${path}mapImg.png`),
  profile: require(`${path}profile.png`),
  splash: require(`${path}splash.png`),
  ourservices: require(`${path}OurServices.png`),
  nearbybarbers: require(`${path}nearbybarbers.png`),
  chatone: require(`${path}barberImage1.png`),
  chattwo: require(`${path}chattwo.png`),
  chatthree: require(`${path}chatthree.png`),
  chatfour: require(`${path}chatfour.png`),
  chatfive: require(`${path}chatfive.png`),
  chatsix: require(`${path}chatsix.png`),
  creditcard: require(`${path}creditcard.png`),
  applepay: require(`${path}applepay.png`),
  paypal: require(`${path}paypal.png`),
  notification: require(`${path}notification.png`),
  notificationone: require(`${path}notification.png`),
  bottomsheetimg: require(`${path}bottomsheetimg.png`),
  Whatsapp: require(`${path}Whatsapp.png`),
  Instagram: require(`${path}Instagram.png`),
  Facebook: require(`${path}Facebook.png`),
  Youtube: require(`${path}Youtube.png`),
  Linkedin: require(`${path}Linkedin.png`),
  Snapchat: require(`${path}Snapchat.png`),
  Transfer: require(`${path}Transfer.png`),
  Transaction: require(`${path}Transaction.png`),
  Atmcard: require(`${path}AtmCard.png`),
  Report: require(`${path}Report.png`),
  UserPage: require(`${path}UserPage.png`),
  SuperAdmin: require(`${path}SuperAdmin.png`),
  visaimg: require(`${path}visaimg.png`),
  barberearbreport: require(`${path}barberearnreport.png`),
  ourservices2: require(`${path}ourservices2.png`),
  ourservices3: require(`${path}ourservices3.png`),
  Percentage: require(`${path}Percentage.png`),
  Editimage:require(`${path}editimage.png`),
  deleteimage:require(`${path}deleteimage.png`),
};
